repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [
            "--fix",
            "--ignore=S603,S110,S311,S112",
            "--ignore=N999,TID251,ANN101,ANN102,BLE001",
            "--ignore=C901,D107,D100,PLR0913,PLR0912",
            "--ignore=D101,D102,D104", # Docstring checks
            "--select=A,B,D,E,F,I,N,Q,R,S,W,UP,C4,C90,ANN,BLE,FBT,ASYNC,COM",
            "--select=PIE,TID,ARG,PTH,PL,EM",
            "--line-length=79",
            "--no-cache",
          ]
        types_or: [python]
      # Run the formatter.
      - id: ruff-format
        args: ["--line-length=79", "--no-cache"]
        types_or: [python]
